# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_gnn/sampler/sampling_spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_gnn/sampler/sampling_spec.proto',
  package='tensorflow_gnn.sampler',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n*tensorflow_gnn/sampler/sampling_spec.proto\x12\x16tensorflow_gnn.sampler\"\x7f\n\x0cSamplingSpec\x12/\n\x07seed_op\x18\x01 \x01(\x0b\x32\x1e.tensorflow_gnn.sampler.SeedOp\x12\x38\n\x0csampling_ops\x18\x02 \x03(\x0b\x32\".tensorflow_gnn.sampler.SamplingOpJ\x04\x08\x03\x10\x05\"6\n\x06SeedOp\x12\x0f\n\x07op_name\x18\x01 \x01(\t\x12\x15\n\rnode_set_name\x18\x02 \x01(\tJ\x04\x08\x03\x10\x05\"\xa3\x01\n\nSamplingOp\x12\x0f\n\x07op_name\x18\x01 \x01(\t\x12\x16\n\x0einput_op_names\x18\x02 \x03(\t\x12\x15\n\redge_set_name\x18\x03 \x01(\t\x12\x13\n\x0bsample_size\x18\x04 \x01(\x05\x12:\n\x08strategy\x18\x05 \x01(\x0e\x32(.tensorflow_gnn.sampler.SamplingStrategyJ\x04\x08\x06\x10\x07*F\n\x10SamplingStrategy\x12\t\n\x05TOP_K\x10\x00\x12\x12\n\x0eRANDOM_UNIFORM\x10\x01\x12\x13\n\x0fRANDOM_WEIGHTED\x10\x02')
)

_SAMPLINGSTRATEGY = _descriptor.EnumDescriptor(
  name='SamplingStrategy',
  full_name='tensorflow_gnn.sampler.SamplingStrategy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOP_K', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANDOM_UNIFORM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANDOM_WEIGHTED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=421,
  serialized_end=491,
)
_sym_db.RegisterEnumDescriptor(_SAMPLINGSTRATEGY)

SamplingStrategy = enum_type_wrapper.EnumTypeWrapper(_SAMPLINGSTRATEGY)
TOP_K = 0
RANDOM_UNIFORM = 1
RANDOM_WEIGHTED = 2



_SAMPLINGSPEC = _descriptor.Descriptor(
  name='SamplingSpec',
  full_name='tensorflow_gnn.sampler.SamplingSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed_op', full_name='tensorflow_gnn.sampler.SamplingSpec.seed_op', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampling_ops', full_name='tensorflow_gnn.sampler.SamplingSpec.sampling_ops', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=197,
)


_SEEDOP = _descriptor.Descriptor(
  name='SeedOp',
  full_name='tensorflow_gnn.sampler.SeedOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_name', full_name='tensorflow_gnn.sampler.SeedOp.op_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_set_name', full_name='tensorflow_gnn.sampler.SeedOp.node_set_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=253,
)


_SAMPLINGOP = _descriptor.Descriptor(
  name='SamplingOp',
  full_name='tensorflow_gnn.sampler.SamplingOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_name', full_name='tensorflow_gnn.sampler.SamplingOp.op_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_op_names', full_name='tensorflow_gnn.sampler.SamplingOp.input_op_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edge_set_name', full_name='tensorflow_gnn.sampler.SamplingOp.edge_set_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_size', full_name='tensorflow_gnn.sampler.SamplingOp.sample_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='tensorflow_gnn.sampler.SamplingOp.strategy', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=419,
)

_SAMPLINGSPEC.fields_by_name['seed_op'].message_type = _SEEDOP
_SAMPLINGSPEC.fields_by_name['sampling_ops'].message_type = _SAMPLINGOP
_SAMPLINGOP.fields_by_name['strategy'].enum_type = _SAMPLINGSTRATEGY
DESCRIPTOR.message_types_by_name['SamplingSpec'] = _SAMPLINGSPEC
DESCRIPTOR.message_types_by_name['SeedOp'] = _SEEDOP
DESCRIPTOR.message_types_by_name['SamplingOp'] = _SAMPLINGOP
DESCRIPTOR.enum_types_by_name['SamplingStrategy'] = _SAMPLINGSTRATEGY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SamplingSpec = _reflection.GeneratedProtocolMessageType('SamplingSpec', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLINGSPEC,
  '__module__' : 'tensorflow_gnn.sampler.sampling_spec_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.sampler.SamplingSpec)
  })
_sym_db.RegisterMessage(SamplingSpec)

SeedOp = _reflection.GeneratedProtocolMessageType('SeedOp', (_message.Message,), {
  'DESCRIPTOR' : _SEEDOP,
  '__module__' : 'tensorflow_gnn.sampler.sampling_spec_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.sampler.SeedOp)
  })
_sym_db.RegisterMessage(SeedOp)

SamplingOp = _reflection.GeneratedProtocolMessageType('SamplingOp', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLINGOP,
  '__module__' : 'tensorflow_gnn.sampler.sampling_spec_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.sampler.SamplingOp)
  })
_sym_db.RegisterMessage(SamplingOp)


# @@protoc_insertion_point(module_scope)
