# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_gnn/sampler/subgraph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.example import feature_pb2 as tensorflow_dot_core_dot_example_dot_feature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_gnn/sampler/subgraph.proto',
  package='tensorflow_gnn.sampler',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n%tensorflow_gnn/sampler/subgraph.proto\x12\x16tensorflow_gnn.sampler\x1a%tensorflow/core/example/feature.proto\"\xfc\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x0c\x12&\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x14.tensorflow.Features\x12\x15\n\rnode_set_name\x18\x04 \x01(\t\x12\x39\n\x0eoutgoing_edges\x18\x03 \x03(\x0b\x32!.tensorflow_gnn.sampler.Node.Edge\x1an\n\x04\x45\x64ge\x12\x13\n\x0bneighbor_id\x18\x01 \x01(\x0c\x12&\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x14.tensorflow.Features\x12\x15\n\redge_set_name\x18\x04 \x01(\t\x12\x12\n\nedge_index\x18\x05 \x01(\x03\"\xb8\x01\n\x08Subgraph\x12\x11\n\tsample_id\x18\x01 \x01(\x0c\x12\x14\n\x0cseed_node_id\x18\x02 \x01(\x0c\x12+\n\x05nodes\x18\x03 \x03(\x0b\x32\x1c.tensorflow_gnn.sampler.Node\x12.\n\x08\x62oundary\x18\x05 \x03(\x0b\x32\x1c.tensorflow_gnn.sampler.Node\x12&\n\x08\x66\x65\x61tures\x18\x04 \x01(\x0b\x32\x14.tensorflow.Features')
  ,
  dependencies=[tensorflow_dot_core_dot_example_dot_feature__pb2.DESCRIPTOR,])




_NODE_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='tensorflow_gnn.sampler.Node.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbor_id', full_name='tensorflow_gnn.sampler.Node.Edge.neighbor_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='tensorflow_gnn.sampler.Node.Edge.features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edge_set_name', full_name='tensorflow_gnn.sampler.Node.Edge.edge_set_name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edge_index', full_name='tensorflow_gnn.sampler.Node.Edge.edge_index', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=357,
)

_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='tensorflow_gnn.sampler.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tensorflow_gnn.sampler.Node.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='tensorflow_gnn.sampler.Node.features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_set_name', full_name='tensorflow_gnn.sampler.Node.node_set_name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outgoing_edges', full_name='tensorflow_gnn.sampler.Node.outgoing_edges', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NODE_EDGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=357,
)


_SUBGRAPH = _descriptor.Descriptor(
  name='Subgraph',
  full_name='tensorflow_gnn.sampler.Subgraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_id', full_name='tensorflow_gnn.sampler.Subgraph.sample_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed_node_id', full_name='tensorflow_gnn.sampler.Subgraph.seed_node_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='tensorflow_gnn.sampler.Subgraph.nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boundary', full_name='tensorflow_gnn.sampler.Subgraph.boundary', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='tensorflow_gnn.sampler.Subgraph.features', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=544,
)

_NODE_EDGE.fields_by_name['features'].message_type = tensorflow_dot_core_dot_example_dot_feature__pb2._FEATURES
_NODE_EDGE.containing_type = _NODE
_NODE.fields_by_name['features'].message_type = tensorflow_dot_core_dot_example_dot_feature__pb2._FEATURES
_NODE.fields_by_name['outgoing_edges'].message_type = _NODE_EDGE
_SUBGRAPH.fields_by_name['nodes'].message_type = _NODE
_SUBGRAPH.fields_by_name['boundary'].message_type = _NODE
_SUBGRAPH.fields_by_name['features'].message_type = tensorflow_dot_core_dot_example_dot_feature__pb2._FEATURES
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Subgraph'] = _SUBGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {

  'Edge' : _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
    'DESCRIPTOR' : _NODE_EDGE,
    '__module__' : 'tensorflow_gnn.sampler.subgraph_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow_gnn.sampler.Node.Edge)
    })
  ,
  'DESCRIPTOR' : _NODE,
  '__module__' : 'tensorflow_gnn.sampler.subgraph_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.sampler.Node)
  })
_sym_db.RegisterMessage(Node)
_sym_db.RegisterMessage(Node.Edge)

Subgraph = _reflection.GeneratedProtocolMessageType('Subgraph', (_message.Message,), {
  'DESCRIPTOR' : _SUBGRAPH,
  '__module__' : 'tensorflow_gnn.sampler.subgraph_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.sampler.Subgraph)
  })
_sym_db.RegisterMessage(Subgraph)


# @@protoc_insertion_point(module_scope)
