licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "homogeneous",
    srcs = [
        ":citrus.pbtxt",
        ":fruits.csv",
        ":one_seed.csv",
        ":sampler_golden.ascii",
        ":tastelike.csv",
        ":two_seeds.csv",
    ],
)
