"""Custom Python configuration for Bazel."""

def _python_repository_impl(repository_ctx):
    """Implementation of custom Python repository rule."""
    python_bin = repository_ctx.os.environ.get("PYTHON_BIN_PATH", "/usr/bin/python3")

    # Generate BUILD file with explicit Python paths
    repository_ctx.file("BUILD", """# Auto-generated by python_configure.bzl
# This file overrides TensorFlow's local_config_python to provide explicit Python paths

load("@bazel_tools//tools/python:toolchain.bzl", "py_runtime_pair")

py_runtime(
    name = "py3_runtime",
    interpreter_path = "{python_bin}",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

py_runtime_pair(
    name = "py_runtime_pair",
    py2_runtime = None,
    py3_runtime = ":py3_runtime",
)

toolchain(
    name = "py_toolchain",
    toolchain = ":py_runtime_pair",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
""".format(python_bin = python_bin))

python_repository = repository_rule(
    implementation = _python_repository_impl,
    environ = ["PYTHON_BIN_PATH"],
    local = True,
)
