# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_gnn/proto/examples.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.example import example_pb2 as tensorflow_dot_core_dot_example_dot_example__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_gnn/proto/examples.proto',
  package='tensorflow_gnn.testdata',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#tensorflow_gnn/proto/examples.proto\x12\x17tensorflow_gnn.testdata\x1a%tensorflow/core/example/example.proto\"4\n\x0b\x45xampleList\x12%\n\x08\x65xamples\x18\x01 \x03(\x0b\x32\x13.tensorflow.Example')
  ,
  dependencies=[tensorflow_dot_core_dot_example_dot_example__pb2.DESCRIPTOR,])




_EXAMPLELIST = _descriptor.Descriptor(
  name='ExampleList',
  full_name='tensorflow_gnn.testdata.ExampleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='examples', full_name='tensorflow_gnn.testdata.ExampleList.examples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=155,
)

_EXAMPLELIST.fields_by_name['examples'].message_type = tensorflow_dot_core_dot_example_dot_example__pb2._EXAMPLE
DESCRIPTOR.message_types_by_name['ExampleList'] = _EXAMPLELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleList = _reflection.GeneratedProtocolMessageType('ExampleList', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLELIST,
  '__module__' : 'tensorflow_gnn.proto.examples_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.testdata.ExampleList)
  })
_sym_db.RegisterMessage(ExampleList)


# @@protoc_insertion_point(module_scope)
