package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_test(
    name = "core_test",
    srcs = ["core_test.py"],
    python_version = "PY3",
    deps = [],
)

py_test(
    name = "ext_ops_test",
    srcs = ["ext_ops_test.py"],
    python_version = "PY3",
    deps = [],
)

py_test(
    name = "eval_dag_test",
    srcs = ["eval_dag_test.py"],
    python_version = "PY3",
    deps = [],
)