seed_op: <
  op_name: 'seed'
  node_set_name: 'nodes'
>
sampling_ops: <
  op_name: 'hop-1'
  input_op_names: [ 'seed' ]
  strategy: TOP_K
  sample_size: 8
  edge_set_name: 'edges'
>
sampling_ops: <
  op_name: 'hop-2'
  input_op_names: [ 'hop-1' ]
  strategy: TOP_K
  sample_size: 3
  edge_set_name: 'edges'
>
