# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_gnn/tools/sampled_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_gnn/tools/sampled_stats.proto',
  package='tensorflow_gnn.stats',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n(tensorflow_gnn/tools/sampled_stats.proto\x12\x14tensorflow_gnn.stats\"}\n\x10GraphTensorStats\x12\x39\n\rfeature_stats\x18\x01 \x03(\x0b\x32\".tensorflow_gnn.stats.FeatureStats\x12.\n\x07samples\x18\x02 \x01(\x0b\x32\x1d.tensorflow_gnn.stats.Samples\"=\n\x07Samples\x12\x32\n\nsize_pairs\x18\x01 \x03(\x0b\x32\x1e.tensorflow_gnn.stats.SizePair\"0\n\x08SizePair\x12\x11\n\tnum_nodes\x18\x01 \x01(\x05\x12\x11\n\tnum_edges\x18\x02 \x01(\x05\"_\n\x05Stats\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\x02\x12\x0c\n\x04mean\x18\x04 \x01(\x02\x12\x0b\n\x03std\x18\x05 \x01(\x02\x12\x11\n\tquantiles\x18\x06 \x03(\x02\"t\n\x0c\x46\x65\x61tureStats\x12\x10\n\x08set_type\x18\x01 \x01(\t\x12\x10\n\x08set_name\x18\x02 \x01(\t\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x03 \x01(\t\x12*\n\x05stats\x18\x04 \x01(\x0b\x32\x1b.tensorflow_gnn.stats.Stats')
)




_GRAPHTENSORSTATS = _descriptor.Descriptor(
  name='GraphTensorStats',
  full_name='tensorflow_gnn.stats.GraphTensorStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_stats', full_name='tensorflow_gnn.stats.GraphTensorStats.feature_stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='tensorflow_gnn.stats.GraphTensorStats.samples', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=191,
)


_SAMPLES = _descriptor.Descriptor(
  name='Samples',
  full_name='tensorflow_gnn.stats.Samples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size_pairs', full_name='tensorflow_gnn.stats.Samples.size_pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=254,
)


_SIZEPAIR = _descriptor.Descriptor(
  name='SizePair',
  full_name='tensorflow_gnn.stats.SizePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_nodes', full_name='tensorflow_gnn.stats.SizePair.num_nodes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_edges', full_name='tensorflow_gnn.stats.SizePair.num_edges', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=304,
)


_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='tensorflow_gnn.stats.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='tensorflow_gnn.stats.Stats.min', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='tensorflow_gnn.stats.Stats.max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='median', full_name='tensorflow_gnn.stats.Stats.median', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean', full_name='tensorflow_gnn.stats.Stats.mean', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='std', full_name='tensorflow_gnn.stats.Stats.std', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantiles', full_name='tensorflow_gnn.stats.Stats.quantiles', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=401,
)


_FEATURESTATS = _descriptor.Descriptor(
  name='FeatureStats',
  full_name='tensorflow_gnn.stats.FeatureStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_type', full_name='tensorflow_gnn.stats.FeatureStats.set_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_name', full_name='tensorflow_gnn.stats.FeatureStats.set_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='tensorflow_gnn.stats.FeatureStats.feature_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='tensorflow_gnn.stats.FeatureStats.stats', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=519,
)

_GRAPHTENSORSTATS.fields_by_name['feature_stats'].message_type = _FEATURESTATS
_GRAPHTENSORSTATS.fields_by_name['samples'].message_type = _SAMPLES
_SAMPLES.fields_by_name['size_pairs'].message_type = _SIZEPAIR
_FEATURESTATS.fields_by_name['stats'].message_type = _STATS
DESCRIPTOR.message_types_by_name['GraphTensorStats'] = _GRAPHTENSORSTATS
DESCRIPTOR.message_types_by_name['Samples'] = _SAMPLES
DESCRIPTOR.message_types_by_name['SizePair'] = _SIZEPAIR
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
DESCRIPTOR.message_types_by_name['FeatureStats'] = _FEATURESTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphTensorStats = _reflection.GeneratedProtocolMessageType('GraphTensorStats', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHTENSORSTATS,
  '__module__' : 'tensorflow_gnn.tools.sampled_stats_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.stats.GraphTensorStats)
  })
_sym_db.RegisterMessage(GraphTensorStats)

Samples = _reflection.GeneratedProtocolMessageType('Samples', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLES,
  '__module__' : 'tensorflow_gnn.tools.sampled_stats_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.stats.Samples)
  })
_sym_db.RegisterMessage(Samples)

SizePair = _reflection.GeneratedProtocolMessageType('SizePair', (_message.Message,), {
  'DESCRIPTOR' : _SIZEPAIR,
  '__module__' : 'tensorflow_gnn.tools.sampled_stats_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.stats.SizePair)
  })
_sym_db.RegisterMessage(SizePair)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {
  'DESCRIPTOR' : _STATS,
  '__module__' : 'tensorflow_gnn.tools.sampled_stats_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.stats.Stats)
  })
_sym_db.RegisterMessage(Stats)

FeatureStats = _reflection.GeneratedProtocolMessageType('FeatureStats', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESTATS,
  '__module__' : 'tensorflow_gnn.tools.sampled_stats_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_gnn.stats.FeatureStats)
  })
_sym_db.RegisterMessage(FeatureStats)


# @@protoc_insertion_point(module_scope)
