licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "heterogeneous",
    srcs = [
        ":creditcard.csv",
        ":customer.csv",
        ":graph.pbtxt",
        ":invalid_customer.csv",
        ":one_customer.csv",
        ":owns_card.csv",
        ":paid_with.csv",
        ":sampler_golden.ascii",
        ":transactions.csv",
        ":two_customers.csv",
    ],
)
