licenses(["notice"])

package(
    default_applicable_licenses = ["//tensorflow_gnn:license"],
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "feature_repr",
    srcs = [
        "feature_repr.pbtxt",
    ],
)
